# Generated by Django 5.1.1 on 2024-11-16 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_sentemail_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentemail',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sentemail',
            name='user_id',
        ),
        migrations.AddField(
            model_name='sentemail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to='backend_api.user', to_field='email'),
        ),
    ]
