name: Django CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: webappdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Grey@1234
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations
      run: |
        source venv/bin/activate
        python3 manage.py makemigrations
        python3 manage.py migrate
      env:
          DATABASE_NAME: webappdb
          DATABASE_USER: postgres
          DATABASE_PASSWORD: Grey@1234
          DATABASE_HOST: 127.0.0.1
          DATABASE_PORT: 5432

    - name: Run tests
      run: |
        source venv/bin/activate
        python3 manage.py test
      env:
          DATABASE_NAME: webappdb
          DATABASE_USER: postgres
          DATABASE_PASSWORD: Grey@1234
          DATABASE_HOST: 127.0.0.1
          DATABASE_PORT: 5432
